services:
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: meroadmin
      WORDPRESS_DB_PASSWORD: IjO3aJEYyh
      WORDPRESS_DB_NAME: meroluga
    ports:
      - "999:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: meroluga
      MYSQL_USER: meroadmin
      MYSQL_PASSWORD: IjO3aJEYyh
      MYSQL_ROOT_PASSWORD: vG8uZqX82I
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
